### ISSUE TITLE
Cross-Origin and XHR Error

### ISSUE THREAD

**Issue by fenpaws** [EdyTheCow/docker-pterodactyl#13]
Hey there, I used your really good repo to set up my own little pterodactyl server. 
Since I already had a Treafeik setup I just adopted the config you wrote. It seems to work fine, Panel is working and if I access the wings directly I also get a JSON response.

But if I check the Panel again for the WIngs it's offline, after a quick look in the console I noticed that it gave me a huge amount of Cross-ORigin and XHR errors. 

It seems that it trys to access the API of the Wing with `https://wings.fenpa.ws:80/api/system`.
It should not add the `:80` right? did I mess something up? 

The auto-redirect works fine for any service I have.

I added two screenshots, if you need more info then I'm more than happy to reply.

<img width="1680" alt="grafik" src="https://user-images.githubusercontent.com/29946173/123540739-d36dcf80-d740-11eb-928f-2f43d8bd7ec0.png">
<img width="1680" alt="grafik" src="https://user-images.githubusercontent.com/29946173/123540750-e2548200-d740-11eb-89b4-d0dc8f4e1f20.png">

**Comment by EdyTheCow** [comment]
Hey! I am glad you found my repository useful :) what did you put as port for wings when setting it up in the panel?

**Comment by fenpaws** [comment]
Wow, you are fast o.0

I did set up the wings to use port 80, as you stated in your Installation. 
But if I use 443 I just get a `bad gateway` error on the wing.

But I had an idea, if you set up the Wing in the Panel to use port 443, and change the copied config to use port 80 instead of port 443 for the API then it works.

```yaml
api:
  host: 0.0.0.0
  port: 80
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/wings.vm.fenpa.ws/fullchain.pem
    key: /etc/letsencrypt/live/wings.vm.fenpa.ws/privkey.pem
  disable_remote_download: false
  upload_limit: 100
```

<img width="922" alt="grafik" src="https://user-images.githubusercontent.com/29946173/123541404-c05cfe80-d744-11eb-8b42-8aca644e13eb.png">

<img width="922" alt="grafik" src="https://user-images.githubusercontent.com/29946173/123541450-fa2e0500-d744-11eb-876d-6357ae965cea.png">
